In [3]:
# csv is a package for file reading/IO
import csv

# pandas is the data analysis library we'll use in this course
import pandas as pd

In [4]:
crime_df = pd.read_csv('crime.csv', header = None, names = ['Dc_Dist', 'Psa', 'Dispatch_Date_Time', 'Dispatch_Date',\
                                                                     'Dispatch_Time', 'Hour', 'Dc_Key','Location_Block', \
                                                                      'UCR_General', 'Text_General_Code', 'Police_Districts', 'Month',\
                                                           'Lon', 'Lat'],dtype="object")

In [5]:
crime_df.dtypes

Dc_Dist               object
Psa                   object
Dispatch_Date_Time    object
Dispatch_Date         object
Dispatch_Time         object
Hour                  object
Dc_Key                object
Location_Block        object
UCR_General           object
Text_General_Code     object
Police_Districts      object
Month                 object
Lon                   object
Lat                   object
dtype: object

In [6]:
# crime_df = crime_df.dropna(subset = ['Dc_Dist', 'Psa', 'Dispatch_Date_Time', 'Dispatch_Date',\
#                                                                      'Dispatch_Time', 'Hour', 'Dc_Key','Location_Block', \
#                                                                       'UCR_General', 'Text_General_Code', 'Police_Districts', 'Month',\
#                                                            'Lon', 'Lat'])

In [7]:
# crime_df['Police_Districts'] = crime_df['Police_Districts'].astype(int)

In [8]:
crime_df = crime_df.drop(['Dc_Dist', 'Psa', 'Dispatch_Date_Time', 'Dispatch_Time', 'Hour', 'Dc_Key', 'UCR_General', 'Text_General_Code', 'Month'], axis=1)

In [9]:
crime_df = crime_df.drop([0])

In [10]:
crime_df

,Dispatch_Date,Location_Block,Police_Districts,Lon,Lat
1,2009-10-02,S 38TH ST / MARKETUT ST,NaN,NaN,NaN
2,2009-05-10,8500 BLOCK MITCH,NaN,NaN,NaN
3,2009-08-07,6TH CAMBRIA,NaN,NaN,NaN
4,2009-07-19,5500 BLOCK N 5TH ST,20,-75.130477,40.036389
5,2009-06-25,1800 BLOCK WYLIE ST,8,-75.16635,39.969532
6,2015-04-25,800 BLOCK S BROAD ST,13,-75.166412,39.94007
7,2009-02-10,2200 BLOCK RIDGE AVE,16,-75.171149,39.979586
8,2009-04-02,TERMINAL A W,NaN,NaN,NaN
9,2009-03-18,N 5TH SOMMERVILLE,NaN,NaN,NaN
10,2009-06-14,N 2828 W MASTER STST,NaN,NaN,NaN
11,2009-01-19,N 2800 ST / DIAMOND ST,NaN,NaN,NaN
12,2009-02-09,2700 BLOCK / 2720 / 2729 WOLF ST,NaN,NaN,NaN
13,2015-10-06,1500 BLOCK N 15TH ST,16,-75.160229,39.976134
14,2015-10-09,1500 BLOCK N 17TH ST,16,-75.163073,39.977872
15,2015-05-03,GATE C-18,NaN,NaN,NaN
16,2015-11-30,6500 BLOCK CASTOR AV,2,-75.075602,40.04127
17,2009-03-12,B-BAGGAGE,NaN,NaN,NaN
18,2009-03-21,N 2237 W OXFORD STRD ST,NaN,NaN,NaN
19,2015-04-11,2800 BLOCK RUTH ST,17,-75.122057,39.990907
20,2009-12-12,N 1200 N 18TH ST,NaN,NaN,NaN
21,2009-08-30,100 BLOCK LEVERING ST / MAIN ST,NaN,NaN,NaN
22,2015-12-10,2600 BLOCK W THOMPSON ST,16,-75.178874,39.975724
23,2009-01-11,5200 BLOCK HARBISON AVE,11,-75.069032,40.01243
24,2009-12-03,N ALDEN / LANSDOWNEWNE AVE,NaN,NaN,NaN
25,2009-05-21,7500 BLOCK WOODBINE AVE,15,-75.266605,39.975197
26,2015-05-05,5600 BLOCK CHESTNUT ST,14,-75.235121,39.959754
27,2015-12-08,4600 BLOCK E ROOSEVELT BLVD,2,-75.099584,40.02849
28,2015-10-13,4800 BLOCK MARKET ST,14,-75.217184,39.959005
29,2015-08-23,3000 BLOCK B ST,17,-75.125869,39.995626
30,2009-04-15,0 BLOCK E HIGH ST,10,-75.1769,40.040153
...,...,...,...,...,...
2237576,2017-01-17,5500 BLOCK WALNUT ST,14,-75.233132,39.957866
2237577,2017-01-17,5700 BLOCK STEWART ST,15,-75.235876,39.977571
2237578,2017-01-17,5200 BLOCK PARKSIDE AVE,15,-75.226947,39.982499
2237579,2017-01-17,1500 BLOCK OVERINGTON ST 2,11,-75.085593,40.016163
2237580,2017-01-17,1100 BLOCK BRISTOL ST,17,-75.10575,40.012844
2237581,2017-01-17,7000 BLOCK ARDLEIGH ST,10,-75.182448,40.062458
2237582,2017-01-17,300 BLOCK S 24TH ST,8,-75.180265,39.948053
2237583,2017-01-17,6100 BLOCK W OXFORD ST,15,-75.243254,39.979961
2237584,2017-01-17,3400 BLOCK GERMANTOWN AV,18,-75.149685,40.005818
2237585,2017-01-17,4200 BLOCK N FRONT ST,18,-75.126,40.014088
2237586,2017-01-17,GERMANTOWN AV / W JUNIATA ST,21,-75.155101,40.018144
2237587,2017-01-17,3100 BLOCK REACH ST,17,-75.116343,39.995302
2237588,2017-01-17,7600 BLOCK OGONTZ AVE,10,-75.157229,40.069988
2237589,2017-01-17,7100 BLOCK OXFORD AVE,2,-75.085731,40.057272
2237590,2017-01-17,6500 BLOCK ELMWOOD AV,9,-75.230404,39.922215
2237591,2017-01-17,800 BLOCK E WOODLAWN ST,10,-75.16376,40.04486
2237592,2017-01-17,3100 BLOCK N FRONT ST,17,-75.129359,39.997859
2237593,2017-01-17,1800 BLOCK S 54TH ST,9,-75.217968,39.935437
2237594,2017-01-17,3300 BLOCK N 22ND ST,21,-75.165378,40.005945
2237595,2017-01-17,2500 BLOCK E DAUPHIN ST 2,19,-75.124246,39.975801
2237596,2017-01-18,1900 BLOCK W OLNEY AVE,20,-75.152872,40.039265
2237597,2017-01-17,0 BLOCK S 52ND ST,14,-75.224941,39.959455
2237598,2017-01-17,4000 BLOCK MARKET,14,-75.201956,39.957158
2237599,2017-01-17,4000 BLOCK MARKET,14,-75.201956,39.957158
2237600,2017-01-17,300 BLOCK S BROAD ST,5,-75.164743,39.946502
2237601,2017-01-17,2100 BLOCK S BROAD ST,1,-75.169992,39.923556
2237602,2017-01-17,N 38TH ST / WALLACE ST,12,-75.197627,39.964593
2237603,2017-01-17,N 38TH ST / WALLACE ST,12,-75.197627,39.964593
2237604,2017-01-18,6000 BLOCK HAVERFORD AV,15,-75.240163,39.970507
2237605,2017-01-17,N 34TH ST / LANCASTER AV,12,-75.191173,39.957305

In [11]:
crime_df.reset_index(drop=True)

,Dispatch_Date,Location_Block,Police_Districts,Lon,Lat
0,2009-10-02,S 38TH ST / MARKETUT ST,NaN,NaN,NaN
1,2009-05-10,8500 BLOCK MITCH,NaN,NaN,NaN
2,2009-08-07,6TH CAMBRIA,NaN,NaN,NaN
3,2009-07-19,5500 BLOCK N 5TH ST,20,-75.130477,40.036389
4,2009-06-25,1800 BLOCK WYLIE ST,8,-75.16635,39.969532
5,2015-04-25,800 BLOCK S BROAD ST,13,-75.166412,39.94007
6,2009-02-10,2200 BLOCK RIDGE AVE,16,-75.171149,39.979586
7,2009-04-02,TERMINAL A W,NaN,NaN,NaN
8,2009-03-18,N 5TH SOMMERVILLE,NaN,NaN,NaN
9,2009-06-14,N 2828 W MASTER STST,NaN,NaN,NaN
10,2009-01-19,N 2800 ST / DIAMOND ST,NaN,NaN,NaN
11,2009-02-09,2700 BLOCK / 2720 / 2729 WOLF ST,NaN,NaN,NaN
12,2015-10-06,1500 BLOCK N 15TH ST,16,-75.160229,39.976134
13,2015-10-09,1500 BLOCK N 17TH ST,16,-75.163073,39.977872
14,2015-05-03,GATE C-18,NaN,NaN,NaN
15,2015-11-30,6500 BLOCK CASTOR AV,2,-75.075602,40.04127
16,2009-03-12,B-BAGGAGE,NaN,NaN,NaN
17,2009-03-21,N 2237 W OXFORD STRD ST,NaN,NaN,NaN
18,2015-04-11,2800 BLOCK RUTH ST,17,-75.122057,39.990907
19,2009-12-12,N 1200 N 18TH ST,NaN,NaN,NaN
20,2009-08-30,100 BLOCK LEVERING ST / MAIN ST,NaN,NaN,NaN
21,2015-12-10,2600 BLOCK W THOMPSON ST,16,-75.178874,39.975724
22,2009-01-11,5200 BLOCK HARBISON AVE,11,-75.069032,40.01243
23,2009-12-03,N ALDEN / LANSDOWNEWNE AVE,NaN,NaN,NaN
24,2009-05-21,7500 BLOCK WOODBINE AVE,15,-75.266605,39.975197
25,2015-05-05,5600 BLOCK CHESTNUT ST,14,-75.235121,39.959754
26,2015-12-08,4600 BLOCK E ROOSEVELT BLVD,2,-75.099584,40.02849
27,2015-10-13,4800 BLOCK MARKET ST,14,-75.217184,39.959005
28,2015-08-23,3000 BLOCK B ST,17,-75.125869,39.995626
29,2009-04-15,0 BLOCK E HIGH ST,10,-75.1769,40.040153
...,...,...,...,...,...
2237575,2017-01-17,5500 BLOCK WALNUT ST,14,-75.233132,39.957866
2237576,2017-01-17,5700 BLOCK STEWART ST,15,-75.235876,39.977571
2237577,2017-01-17,5200 BLOCK PARKSIDE AVE,15,-75.226947,39.982499
2237578,2017-01-17,1500 BLOCK OVERINGTON ST 2,11,-75.085593,40.016163
2237579,2017-01-17,1100 BLOCK BRISTOL ST,17,-75.10575,40.012844
2237580,2017-01-17,7000 BLOCK ARDLEIGH ST,10,-75.182448,40.062458
2237581,2017-01-17,300 BLOCK S 24TH ST,8,-75.180265,39.948053
2237582,2017-01-17,6100 BLOCK W OXFORD ST,15,-75.243254,39.979961
2237583,2017-01-17,3400 BLOCK GERMANTOWN AV,18,-75.149685,40.005818
2237584,2017-01-17,4200 BLOCK N FRONT ST,18,-75.126,40.014088
2237585,2017-01-17,GERMANTOWN AV / W JUNIATA ST,21,-75.155101,40.018144
2237586,2017-01-17,3100 BLOCK REACH ST,17,-75.116343,39.995302
2237587,2017-01-17,7600 BLOCK OGONTZ AVE,10,-75.157229,40.069988
2237588,2017-01-17,7100 BLOCK OXFORD AVE,2,-75.085731,40.057272
2237589,2017-01-17,6500 BLOCK ELMWOOD AV,9,-75.230404,39.922215
2237590,2017-01-17,800 BLOCK E WOODLAWN ST,10,-75.16376,40.04486
2237591,2017-01-17,3100 BLOCK N FRONT ST,17,-75.129359,39.997859
2237592,2017-01-17,1800 BLOCK S 54TH ST,9,-75.217968,39.935437
2237593,2017-01-17,3300 BLOCK N 22ND ST,21,-75.165378,40.005945
2237594,2017-01-17,2500 BLOCK E DAUPHIN ST 2,19,-75.124246,39.975801
2237595,2017-01-18,1900 BLOCK W OLNEY AVE,20,-75.152872,40.039265
2237596,2017-01-17,0 BLOCK S 52ND ST,14,-75.224941,39.959455
2237597,2017-01-17,4000 BLOCK MARKET,14,-75.201956,39.957158
2237598,2017-01-17,4000 BLOCK MARKET,14,-75.201956,39.957158
2237599,2017-01-17,300 BLOCK S BROAD ST,5,-75.164743,39.946502
2237600,2017-01-17,2100 BLOCK S BROAD ST,1,-75.169992,39.923556
2237601,2017-01-17,N 38TH ST / WALLACE ST,12,-75.197627,39.964593
2237602,2017-01-17,N 38TH ST / WALLACE ST,12,-75.197627,39.964593
2237603,2017-01-18,6000 BLOCK HAVERFORD AV,15,-75.240163,39.970507
2237604,2017-01-17,N 34TH ST / LANCASTER AV,12,-75.191173,39.957305

In [12]:
crime_df['Dispatch_Date'] = pd.to_datetime(crime_df['Dispatch_Date'])
crime_df['Lon'] = crime_df['Lon'].astype(float)
crime_df['Lat'] = crime_df['Lat'].astype(float)

In [13]:
crime_df.dtypes

Dispatch_Date       datetime64[ns]
Location_Block              object
Police_Districts            object
Lon                        float64
Lat                        float64
dtype: object

In [14]:
import sqlite3
engine = sqlite3.connect('cis550project_DB')

In [15]:
crime_df.to_sql('crime', engine, if_exists = 'replace', index = False)

In [17]:
crime_df.to_csv('crime_df.csv')